In [237]:
import torch
import pandas as pd
import numpy as np

In [238]:
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

In [239]:
import matplotlib.pyplot as plt

In [240]:
train_df.head()

id  allelectrons_Total  density_Total  allelectrons_Average  val_e_Average  \
0   0               100.0       0.841611                  10.0            4.8   
1   1               100.0       7.558488                  10.0            4.8   
2   2                76.0       8.885992                  15.6            5.6   
3   3               100.0       8.795296                  10.0            4.8   
4   4               116.0       9.577996                  11.6            4.8   

   atomicweight_Average  ionenergy_Average  el_neg_chi_Average  \
0             20.612526           11.08810               2.766   
1             20.298893           12.04083               2.755   
2             33.739258           12.08630               2.828   
3             20.213349           10.94850               2.648   
4             24.988133           11.82448               2.766   

   R_vdw_element_Average  R_cov_element_Average  zaratio_Average  \
0                  1.732                  0.860         0.496070   
1                  1.631                  0.910         0.492719   
2                  1.788                  0.864         0.481478   
3                  1.626                  0.936         0.489272   
4                  1.682                  0.896         0.492736   

   density_Average  Hardness  
0          0.91457       6.0  
1          0.71760       6.5  
2          1.50633       2.5  
3          0.78937       6.0  
4          1.86481       6.0

In [241]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10407 entries, 0 to 10406
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     10407 non-null  int64  
 1   allelectrons_Total     10407 non-null  float64
 2   density_Total          10407 non-null  float64
 3   allelectrons_Average   10407 non-null  float64
 4   val_e_Average          10407 non-null  float64
 5   atomicweight_Average   10407 non-null  float64
 6   ionenergy_Average      10407 non-null  float64
 7   el_neg_chi_Average     10407 non-null  float64
 8   R_vdw_element_Average  10407 non-null  float64
 9   R_cov_element_Average  10407 non-null  float64
 10  zaratio_Average        10407 non-null  float64
 11  density_Average        10407 non-null  float64
 12  Hardness               10407 non-null  float64
dtypes: float64(12), int64(1)
memory usage: 1.0 MB


In [242]:
train_df.describe()

id  allelectrons_Total  density_Total  allelectrons_Average  \
count  10407.00000        10407.000000   10407.000000          10407.000000   
mean    5203.00000          128.053516      14.491342             17.033222   
std     3004.38646          224.123776      15.972877             10.468734   
min        0.00000            0.000000       0.000000              0.000000   
25%     2601.50000           68.000000       7.558488             10.000000   
50%     5203.00000          100.000000      10.650000             12.600000   
75%     7804.50000          131.000000      16.676996             22.000000   
max    10406.00000        15300.000000     643.093804             67.000000   

       val_e_Average  atomicweight_Average  ionenergy_Average  \
count   10407.000000          10407.000000       10407.000000   
mean        4.546789             37.507703          10.938308   
std         0.690864             26.012313           1.408276   
min         0.000000              0.000000           0.000000   
25%         4.000000             20.298893          10.590660   
50%         4.714286             26.203827          11.202760   
75%         4.800000             48.719500          11.670725   
max         6.000000            167.400000          15.245810   

       el_neg_chi_Average  R_vdw_element_Average  R_cov_element_Average  \
count        10407.000000           10407.000000           10407.000000   
mean             2.607662               1.731330               0.944132   
std              0.334906               0.192481               0.180017   
min              0.000000               0.000000               0.000000   
25%              2.530000               1.672500               0.864000   
50%              2.706000               1.732727               0.915556   
75%              2.805000               1.800000               0.981667   
max              3.443000               2.250000               1.615840   

       zaratio_Average  density_Average      Hardness  
count     10407.000000     10407.000000  10407.000000  
mean          0.493349         2.132984      4.647126  
std           0.063080         1.936656      1.680525  
min           0.000000         0.000000      1.000000  
25%           0.476196         0.814800      3.000000  
50%           0.488550         1.351550      5.500000  
75%           0.496070         2.741550      6.000000  
max           0.825990        10.970000     10.000000

In [243]:
from sklearn.preprocessing import MinMaxScaler

In [244]:
MM = MinMaxScaler()
train_vars = [i for i in train_df.columns if i not in ["id","Hardness"]]
# MM.fit(train_df[train_vars])
train_df[train_vars] = MM.fit_transform(train_df[train_vars])
test_df[train_vars] = MM.fit_transform(test_df[train_vars])

In [245]:
train_df.head()

id  allelectrons_Total  density_Total  allelectrons_Average  val_e_Average  \
0   0            0.006536       0.001309              0.149254       0.800000   
1   1            0.006536       0.011753              0.149254       0.800000   
2   2            0.004967       0.013818              0.232836       0.933333   
3   3            0.006536       0.013677              0.149254       0.800000   
4   4            0.007582       0.014894              0.173134       0.800000   

   atomicweight_Average  ionenergy_Average  el_neg_chi_Average  \
0              0.123133           0.727288            0.803369   
1              0.121260           0.789780            0.800174   
2              0.201549           0.792762            0.821377   
3              0.120749           0.718132            0.769097   
4              0.149272           0.775589            0.803369   

   R_vdw_element_Average  R_cov_element_Average  zaratio_Average  \
0               0.769778               0.532231         0.600576   
1               0.724889               0.563175         0.596519   
2               0.794667               0.534706         0.582910   
3               0.722667               0.579265         0.592346   
4               0.747556               0.554510         0.596540   

   density_Average  Hardness  
0         0.083370       6.0  
1         0.065415       6.5  
2         0.137314       2.5  
3         0.071957       6.0  
4         0.169992       6.0

In [246]:
test_df.head()

id  allelectrons_Total  density_Total  allelectrons_Average  \
0  10407            0.087386       0.188806              0.527761   
1  10408            0.008897       0.015444              0.268657   
2  10409            0.011467       0.012079              0.173134   
3  10410            0.009885       0.014163              0.149254   
4  10411            0.005437       0.006267              0.164179   

   val_e_Average  atomicweight_Average  ionenergy_Average  el_neg_chi_Average  \
0       0.880000              0.493197           0.614620            0.667441   
1       0.933333              0.236368           0.792762            0.832994   
2       0.800000              0.138780           0.723073            0.767935   
3       0.800000              0.121260           0.792762            0.821377   
4       0.666667              0.137262           0.739938            0.713041   

   R_vdw_element_Average  R_cov_element_Average  zaratio_Average  \
0               0.847644               0.742881         0.559207   
1               0.734222               0.534874         0.576515   
2               0.797333               0.594305         0.604746   
3               0.738667               0.490301         0.600244   
4               0.777778               0.553033         0.576393   

   density_Average  
0         0.163591  
1         0.128709  
2         0.071863  
3         0.109814  
4         0.085192

In [247]:
from sklearn.model_selection import train_test_split

In [248]:
X = train_df.drop(["id","Hardness"],axis=1)
y = train_df["Hardness"]

In [249]:
X = X.values
y = y.values

In [250]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [251]:
X_train = torch.FloatTensor(X_train)
X_test =  torch.FloatTensor(X_test)

In [252]:
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [253]:
y_train.dtype

torch.int64

In [254]:
from torch import nn

In [255]:
X_train.shape

torch.Size([7805, 11])

In [256]:
import torch.nn.functional as F

In [257]:
class HardnessPrediction(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_1 = nn.Linear(in_features= 11,out_features= 110)
        self.linear_2 = nn.Linear(in_features=110,out_features=220)
        self.linear_3 = nn.Linear(in_features=220,out_features=110)
        self.linear_4 = nn.Linear(in_features=110,out_features=11)
        self.linear_5 = nn.Linear(in_features=11,out_features=1)
        
    def forward(self,x):
        x = self.linear_1(x)
        x = F.relu(x)
        x = F.relu(self.linear_2(x))
        x = F.relu(self.linear_3(x))
        x = F.relu(self.linear_4(x))
        x = F.relu(self.linear_5(x))
        
        return x

In [258]:
model_0 = HardnessPrediction()
# model_0.state_dict()
model_0

HardnessPrediction(
  (linear_1): Linear(in_features=11, out_features=110, bias=True)
  (linear_2): Linear(in_features=110, out_features=220, bias=True)
  (linear_3): Linear(in_features=220, out_features=110, bias=True)
  (linear_4): Linear(in_features=110, out_features=11, bias=True)
  (linear_5): Linear(in_features=11, out_features=1, bias=True)
)

In [267]:
# loss_fn = nn.L1Loss()
loss_fn = F.l1_loss
optimizer = torch.optim.SGD(params = model_0.parameters(),lr = 0.001)

In [268]:
torch.manual_seed(42)
epochs = 100

for epoch in range(epochs):
    model_0.train()
    
    y_pred = model_0(X_train)
    
    loss = loss_fn(y_pred,y_train)
    
    optimizer.zero_grad()
    
    loss.backward()
    
    optimizer.step()
    
    model_0.eval()
    
    with torch.inference_mode():
        test_pred = model_0(X_test)
        
        test_loss = loss_fn(test_pred.squeeze(),y_test)
        
    if epoch % 10 == 0:
        print(f"Epochs: {epoch} | Loss: {loss:.4f} | Test Loss: {test_loss:.4f}")

C:\Users\USER\AppData\Local\Temp\ipykernel_4648\1652484618.py:9: UserWarning: Using a target size (torch.Size([7805])) that is different to the input size (torch.Size([7805, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = loss_fn(y_pred,y_train)


Epochs: 0 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 10 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 20 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 30 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 40 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 50 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 60 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 70 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 80 | Loss: 4.2897 | Test Loss: 4.2652
Epochs: 90 | Loss: 4.2897 | Test Loss: 4.2652


In [269]:
test_pred.squeeze()

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [270]:
y_test

tensor([5, 7, 2,  ..., 6, 5, 6])

In [ ]:
test_id = test_df["id"]
test_df.drop('id',axis = 1,inplace = True)

In [ ]:
test_df = test_df.values
test_df = torch.FloatTensor(test_df)

In [ ]:
pred = model_0(test_df)
pred

In [266]:
y_test

tensor([5, 7, 2,  ..., 6, 5, 6])

In [ ]:
model_0.eval()
with torch.inference_mode():
    